### PR TITLE
Translated the bot

### PR DESCRIPTION
**Pull request by j4cobgarby**
I don't know if I've done exactly what you wanted, it wasn't overly clear.

I created a new file for the translations, but I wasn't sure if you wanted this, or if you wanted it as another function. If this isn't what you wanted, I'd be happy to change it.

### CODE REVIEW

**Comment by wolframtheta** [comment]
Yeah its okey. It's true that it's not clear if you have to create another file or not.. I will modify it.

**Comment by yotam180** [comment]
@wolframtheta maybe it's possible to create a helpful documentation for the language API to make it clearer

**Comment by j4cobgarby** [comment]
@yotam180 @wolframtheta I agree, maybe in a `CONTRIBUTING.md` file. If the current translations are implemented incorrectly, though, I'd be happy to correct them.

**Comment by yotam180** [comment]
The current translations are provided just as they should be. It just seemed to me that you were uncertain about the way you should implement them so I concluded that it was not clear enough. Am I right?

**Comment by j4cobgarby** [comment]
You're right - until now I wasn't sure if they were implemented properly.

**Comment by wolframtheta** [comment]
You have the instructions here https://github.com/wolframtheta/BotCRUPC/issues/1

**Pull request merged**
